version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: vestFut
    environment:
      POSTGRES_USER: vest_fut_adm
      POSTGRES_PASSWORD: vest_fut_1234
      POSTGRES_DB: vest_fut
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
