spring:
  application:
    name: vest_fut
  datasource:
    url: jdbc:postgresql://localhost:5432/vest_fut
    username: vest_fut_adm
    password: vest_fut_1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  messages:
    encoding: UTF-8

server:
  port: 80
  error:
    whitelabel:
      enabled: false
    path: /error