CREATE TABLE order_items
(
    ori_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ori_price    NUMERIC(38, 2) NOT NULL,
    ori_quantity INTEGER        NOT NULL,
    ord_id       BIGINT         NOT NULL
        CONSTRAINT order_items_order_fk
            REFERENCES orders,
    pdt_id       BIGINT         NOT NULL
        CONSTRAINT order_items_product_fk
            REFERENCES products
);