CREATE TABLE payments
(
    pym_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pym_amount  NUMERIC(38, 2) NOT NULL,
    pym_details VARCHAR(255),
    pym_method  VARCHAR(255)   NOT NULL
        CONSTRAINT payments_method_check
            CHECK ((pym_method)::text = ANY
        ((ARRAY ['CARTAO':: character varying, 'CUPOM':: character varying])::text[])
) ,
    ord_id      BIGINT NOT NULL
        CONSTRAINT payments_order_fk
            REFERENCES orders
);
