CREATE TABLE cart_items
(
    cti_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cti_quantity    INTEGER        NOT NULL,
    cti_total_price NUMERIC(38, 2) NOT NULL,
    cart_id         BIGINT         NOT NULL
        CONSTRAINT cart_items_cart_fk
            REFERENCES public.carts,
    pdt_id          BIGINT         NOT NULL
        CONSTRAINT cart_items_product_fk
            REFERENCES products
);
