CREATE TABLE cupons
(
    cup_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cup_code                VARCHAR(20) NOT NULL,
    cup_type                VARCHAR(20) NOT NULL,
    cup_discount_percentage DECIMAL(5, 2),
    cup_amount              DECIMAL(10, 2),
    usr_id                  BIGINT      NOT NULL,
    cup_used                BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user FOREIGN KEY (usr_id) REFERENCES users (id)
);
