CREATE TABLE orders_sends
(
    ors_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ors_ord_id         BIGINT         NOT NULL,
    ors_adr_id         BIGINT         NOT NULL,
    ors_init_date_pred DATE           NOT NULL,
    ors_init_date_real DATE,
    ors_end_date_pred  DATE           NOT NULL,
    ors_end_date_real  DATE,
    ors_frete_price    DECIMAL(10, 2) NOT NULL,

    CONSTRAINT fk_order FOREIGN KEY (ors_ord_id) REFERENCES orders (ord_id),
    CONSTRAINT fk_address FOREIGN KEY (ors_adr_id) REFERENCES addresses (adr_id)
);
