create table users
(
    id              bigint generated by default as identity primary key,
    user_active     boolean      not null,
    user_cpf        varchar(255) not null
        constraint uq_users_cpf unique,
    user_created_at timestamp(6),
    user_email      varchar(255) not null
        constraint uq_users_email unique,
    user_gender     varchar(255) not null
        constraint chk_users_gender check (user_gender in ('MALE', 'FEMALE', 'OTHER')),
    user_name       varchar(255) not null,
    user_password   varchar(255) not null,
    user_phone      varchar(255) not null,
    user_updated_at timestamp(6)
);