create table addresses
(
    adr_id           bigint generated by default as identity primary key,
    adr_city         varchar(50)  not null,
    adr_complement   varchar(50),
    adr_neighborhood varchar(50)  not null,
    adr_number       varchar(10)  not null,
    adr_state        varchar(2)   not null,
    adr_street       varchar(100) not null,
    adr_zip_code     varchar(10)  not null,
    user_id          bigint
        constraint fk_addresses_user_id references users
);

