CREATE TABLE products
(
    pdt_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pdt_description VARCHAR(255),
    pdt_name        VARCHAR(255)   NOT NULL,
    pdt_price       NUMERIC(38, 2) NOT NULL,
    pdt_size        VARCHAR(255),
    pdt_stock       INTEGER NOT NULL DEFAULT 0
);
